#!/usr/bin/env bash
# this file is meant to transfer a file from client to server
if ["$#" -lt 4]; then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
elif ["$#" -lt 3]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TOSSH_KEY"
else
    scp -i "$4" -o STrictHostKeyChecking=no "$1" "$3@$2":~/
fi
