#!/usr/bin/env bash
#generating an ssh key with specifig flags for each item required
private_key="school"

key_bits=4096

passphrase="betty"
ssh-keygen -t rsa -b $key_bits -f ~/.ssh/$private_key -N "$passphrase"
